//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public string description { get; set; }
        public string pcategory { get; set; }
        public int basicprice { get; set; }
        public Nullable<int> discountprice { get; set; }
        public Nullable<int> cid { get; set; }
    
        public virtual category category { get; set; }
    }
}
